local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "Demon_Hunter_Crest", [[Interface\Addons\SharedMedia_MyMedia\background\Demon_Hunter_Crest.tga]]) 
LSM:Register("background", "Druid_Crest", [[Interface\Addons\SharedMedia_MyMedia\background\Druid_Crest.tga]]) 
LSM:Register("background", "Hunter_crest", [[Interface\Addons\SharedMedia_MyMedia\background\Hunter_crest.tga]]) 
LSM:Register("background", "Mage_crest", [[Interface\Addons\SharedMedia_MyMedia\background\Mage_crest.tga]]) 
LSM:Register("background", "Paladin_Crest", [[Interface\Addons\SharedMedia_MyMedia\background\Paladin_Crest.tga]]) 
LSM:Register("background", "Priest_Crest", [[Interface\Addons\SharedMedia_MyMedia\background\Priest_Crest.tga]]) 
LSM:Register("background", "Rogue_Crest", [[Interface\Addons\SharedMedia_MyMedia\background\Rogue_Crest.tga]]) 
LSM:Register("background", "TIME_BAR", [[Interface\Addons\SharedMedia_MyMedia\background\TIME_BAR.tga]]) 
LSM:Register("background", "TIME_BAR_L", [[Interface\Addons\SharedMedia_MyMedia\background\TIME_BAR_L.tga]]) 
LSM:Register("background", "TIME_BAR_R", [[Interface\Addons\SharedMedia_MyMedia\background\TIME_BAR_R.tga]]) 
LSM:Register("background", "Warlock_Crest", [[Interface\Addons\SharedMedia_MyMedia\background\Warlock_Crest.tga]]) 
LSM:Register("background", "Warrior_crest", [[Interface\Addons\SharedMedia_MyMedia\background\Warrior_crest.tga]]) 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----
LSM:Register("font", "Adumu", [[Interface\Addons\SharedMedia_MyMedia\font\Adumu.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "armyrangersexpand", [[Interface\Addons\SharedMedia_MyMedia\font\armyrangersexpand.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "armyrangersexpandital", [[Interface\Addons\SharedMedia_MyMedia\font\armyrangersexpandital.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "armyrangerssuperexpand", [[Interface\Addons\SharedMedia_MyMedia\font\armyrangerssuperexpand.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "BEST IN CLASS", [[Interface\Addons\SharedMedia_MyMedia\font\BEST IN CLASS.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Broken", [[Interface\Addons\SharedMedia_MyMedia\font\Broken.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Kor_1", [[Interface\Addons\SharedMedia_MyMedia\font\Kor_1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_10", [[Interface\Addons\SharedMedia_MyMedia\font\kor_10.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_11-1", [[Interface\Addons\SharedMedia_MyMedia\font\kor_11-1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_11", [[Interface\Addons\SharedMedia_MyMedia\font\kor_11.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Kor_12 B", [[Interface\Addons\SharedMedia_MyMedia\font\Kor_12 B.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_12 M", [[Interface\Addons\SharedMedia_MyMedia\font\kor_12 M.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_12", [[Interface\Addons\SharedMedia_MyMedia\font\kor_12.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_13", [[Interface\Addons\SharedMedia_MyMedia\font\kor_13.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Kor_14", [[Interface\Addons\SharedMedia_MyMedia\font\Kor_14.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Kor_15", [[Interface\Addons\SharedMedia_MyMedia\font\Kor_15.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_2-1", [[Interface\Addons\SharedMedia_MyMedia\font\kor_2-1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_2", [[Interface\Addons\SharedMedia_MyMedia\font\kor_2.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_3-1", [[Interface\Addons\SharedMedia_MyMedia\font\kor_3-1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_3", [[Interface\Addons\SharedMedia_MyMedia\font\kor_3.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_4-1", [[Interface\Addons\SharedMedia_MyMedia\font\kor_4-1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_4", [[Interface\Addons\SharedMedia_MyMedia\font\kor_4.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Kor_5", [[Interface\Addons\SharedMedia_MyMedia\font\Kor_5.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_7", [[Interface\Addons\SharedMedia_MyMedia\font\kor_7.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_8", [[Interface\Addons\SharedMedia_MyMedia\font\kor_8.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_9-1", [[Interface\Addons\SharedMedia_MyMedia\font\kor_9-1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "kor_9", [[Interface\Addons\SharedMedia_MyMedia\font\kor_9.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "MMA-champ_1", [[Interface\Addons\SharedMedia_MyMedia\font\MMA-champ_1.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Rocket-Rinder", [[Interface\Addons\SharedMedia_MyMedia\font\Rocket-Rinder.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "sd hall 4", [[Interface\Addons\SharedMedia_MyMedia\font\sd hall 4.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Sectar", [[Interface\Addons\SharedMedia_MyMedia\font\Sectar.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Sectar_SP", [[Interface\Addons\SharedMedia_MyMedia\font\Sectar_SP.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Stable", [[Interface\Addons\SharedMedia_MyMedia\font\Stable.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "Unboxing", [[Interface\Addons\SharedMedia_MyMedia\font\Unboxing.ttf]], LSM.LOCALE_BIT_koKR) 
LSM:Register("font", "WarWound_1", [[Interface\Addons\SharedMedia_MyMedia\font\WarWound_1.ttf]], LSM.LOCALE_BIT_koKR) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "1", [[Interface\Addons\SharedMedia_MyMedia\sound\1.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "10", [[Interface\Addons\SharedMedia_MyMedia\sound\10.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "2", [[Interface\Addons\SharedMedia_MyMedia\sound\2.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "3", [[Interface\Addons\SharedMedia_MyMedia\sound\3.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "4", [[Interface\Addons\SharedMedia_MyMedia\sound\4.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "5", [[Interface\Addons\SharedMedia_MyMedia\sound\5.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "6", [[Interface\Addons\SharedMedia_MyMedia\sound\6.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "7", [[Interface\Addons\SharedMedia_MyMedia\sound\7.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "8", [[Interface\Addons\SharedMedia_MyMedia\sound\8.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "9", [[Interface\Addons\SharedMedia_MyMedia\sound\9.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Add", [[Interface\Addons\SharedMedia_MyMedia\sound\Add.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Adds", [[Interface\Addons\SharedMedia_MyMedia\sound\Adds.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Avoid", [[Interface\Addons\SharedMedia_MyMedia\sound\Avoid.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Backup", [[Interface\Addons\SharedMedia_MyMedia\sound\Backup.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Bait", [[Interface\Addons\SharedMedia_MyMedia\sound\Bait.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Beam", [[Interface\Addons\SharedMedia_MyMedia\sound\Beam.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Behind", [[Interface\Addons\SharedMedia_MyMedia\sound\Behind.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Bloodlust", [[Interface\Addons\SharedMedia_MyMedia\sound\Bloodlust.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Blue", [[Interface\Addons\SharedMedia_MyMedia\sound\Blue.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack01", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack01.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack02", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack02.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack03", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack03.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack04", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack04.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack05", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack05.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack06", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack06.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack07", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack07.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowPullBack08", [[Interface\Addons\SharedMedia_MyMedia\sound\BowPullBack08.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowRelease01", [[Interface\Addons\SharedMedia_MyMedia\sound\BowRelease01.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowRelease02", [[Interface\Addons\SharedMedia_MyMedia\sound\BowRelease02.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowRelease03", [[Interface\Addons\SharedMedia_MyMedia\sound\BowRelease03.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowRelease04", [[Interface\Addons\SharedMedia_MyMedia\sound\BowRelease04.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowRelease05", [[Interface\Addons\SharedMedia_MyMedia\sound\BowRelease05.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "BowRelease06", [[Interface\Addons\SharedMedia_MyMedia\sound\BowRelease06.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Break", [[Interface\Addons\SharedMedia_MyMedia\sound\Break.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Buff", [[Interface\Addons\SharedMedia_MyMedia\sound\Buff.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "CC", [[Interface\Addons\SharedMedia_MyMedia\sound\CC.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Center", [[Interface\Addons\SharedMedia_MyMedia\sound\Center.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Clear", [[Interface\Addons\SharedMedia_MyMedia\sound\Clear.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Collect", [[Interface\Addons\SharedMedia_MyMedia\sound\Collect.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Dance", [[Interface\Addons\SharedMedia_MyMedia\sound\Dance.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Debuff", [[Interface\Addons\SharedMedia_MyMedia\sound\Debuff.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Dispell", [[Interface\Addons\SharedMedia_MyMedia\sound\Dispell.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Dodge", [[Interface\Addons\SharedMedia_MyMedia\sound\Dodge.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Dont Move", [[Interface\Addons\SharedMedia_MyMedia\sound\Dont Move.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Enter", [[Interface\Addons\SharedMedia_MyMedia\sound\Enter.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Escort", [[Interface\Addons\SharedMedia_MyMedia\sound\Escort.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Fixate", [[Interface\Addons\SharedMedia_MyMedia\sound\Fixate.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Front", [[Interface\Addons\SharedMedia_MyMedia\sound\Front.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Gate", [[Interface\Addons\SharedMedia_MyMedia\sound\Gate.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Gather", [[Interface\Addons\SharedMedia_MyMedia\sound\Gather.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Green", [[Interface\Addons\SharedMedia_MyMedia\sound\Green.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "gun_laser_fire", [[Interface\Addons\SharedMedia_MyMedia\sound\gun_laser_fire.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "gun_laser_fire2", [[Interface\Addons\SharedMedia_MyMedia\sound\gun_laser_fire2.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "gun_laser_reload", [[Interface\Addons\SharedMedia_MyMedia\sound\gun_laser_reload.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_reload_01", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_reload_01.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_reload_02", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_reload_02.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_reload_03", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_reload_03.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_reload_04", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_reload_04.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_reload_05", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_reload_05.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_reload_06", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_reload_06.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_weaponfire_01", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_weaponfire_01.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_weaponfire_02", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_weaponfire_02.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_weaponfire_03", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_weaponfire_03.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_weaponfire_04", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_weaponfire_04.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_weaponfire_05", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_weaponfire_05.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "GUN_weaponfire_06", [[Interface\Addons\SharedMedia_MyMedia\sound\GUN_weaponfire_06.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Healcd", [[Interface\Addons\SharedMedia_MyMedia\sound\Healcd.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Hide", [[Interface\Addons\SharedMedia_MyMedia\sound\Hide.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "High Energy", [[Interface\Addons\SharedMedia_MyMedia\sound\High Energy.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "High Stacks", [[Interface\Addons\SharedMedia_MyMedia\sound\High Stacks.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Immunity", [[Interface\Addons\SharedMedia_MyMedia\sound\Immunity.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "In", [[Interface\Addons\SharedMedia_MyMedia\sound\In.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Intermission", [[Interface\Addons\SharedMedia_MyMedia\sound\Intermission.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Interrupt", [[Interface\Addons\SharedMedia_MyMedia\sound\Interrupt.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Invisibility", [[Interface\Addons\SharedMedia_MyMedia\sound\Invisibility.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Knock", [[Interface\Addons\SharedMedia_MyMedia\sound\Knock.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Left", [[Interface\Addons\SharedMedia_MyMedia\sound\Left.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Linked", [[Interface\Addons\SharedMedia_MyMedia\sound\Linked.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Melee", [[Interface\Addons\SharedMedia_MyMedia\sound\Melee.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Moon", [[Interface\Addons\SharedMedia_MyMedia\sound\Moon.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Move", [[Interface\Addons\SharedMedia_MyMedia\sound\Move.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Next", [[Interface\Addons\SharedMedia_MyMedia\sound\Next.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Orange", [[Interface\Addons\SharedMedia_MyMedia\sound\Orange.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Orb", [[Interface\Addons\SharedMedia_MyMedia\sound\Orb.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Out", [[Interface\Addons\SharedMedia_MyMedia\sound\Out.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Overlap", [[Interface\Addons\SharedMedia_MyMedia\sound\Overlap.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Phase2", [[Interface\Addons\SharedMedia_MyMedia\sound\Phase2.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Phase3", [[Interface\Addons\SharedMedia_MyMedia\sound\Phase3.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Pots", [[Interface\Addons\SharedMedia_MyMedia\sound\Pots.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Purple", [[Interface\Addons\SharedMedia_MyMedia\sound\Purple.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Range", [[Interface\Addons\SharedMedia_MyMedia\sound\Range.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Ready", [[Interface\Addons\SharedMedia_MyMedia\sound\Ready.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Red", [[Interface\Addons\SharedMedia_MyMedia\sound\Red.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Right", [[Interface\Addons\SharedMedia_MyMedia\sound\Right.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Selfcd", [[Interface\Addons\SharedMedia_MyMedia\sound\Selfcd.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Soak", [[Interface\Addons\SharedMedia_MyMedia\sound\Soak.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Soon", [[Interface\Addons\SharedMedia_MyMedia\sound\Soon.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Spellsteal", [[Interface\Addons\SharedMedia_MyMedia\sound\Spellsteal.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Split", [[Interface\Addons\SharedMedia_MyMedia\sound\Split.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Spread", [[Interface\Addons\SharedMedia_MyMedia\sound\Spread.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Stack", [[Interface\Addons\SharedMedia_MyMedia\sound\Stack.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Stop", [[Interface\Addons\SharedMedia_MyMedia\sound\Stop.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Stopcast", [[Interface\Addons\SharedMedia_MyMedia\sound\Stopcast.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Switch", [[Interface\Addons\SharedMedia_MyMedia\sound\Switch.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Targeted", [[Interface\Addons\SharedMedia_MyMedia\sound\Targeted.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Taunt", [[Interface\Addons\SharedMedia_MyMedia\sound\Taunt.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Transition", [[Interface\Addons\SharedMedia_MyMedia\sound\Transition.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Trap", [[Interface\Addons\SharedMedia_MyMedia\sound\Trap.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Turn", [[Interface\Addons\SharedMedia_MyMedia\sound\Turn.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.1", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.1.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.10", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.10.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.2", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.2.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.3", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.3.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.4", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.4.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.5", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.5.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.6", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.6.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.7", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.7.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.8", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.8.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "wagerssi.9", [[Interface\Addons\SharedMedia_MyMedia\sound\wagerssi.9.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "WeaponFire_01", [[Interface\Addons\SharedMedia_MyMedia\sound\WeaponFire_01.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "WeaponFire_02", [[Interface\Addons\SharedMedia_MyMedia\sound\WeaponFire_02.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "WeaponFire_03", [[Interface\Addons\SharedMedia_MyMedia\sound\WeaponFire_03.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "WeaponFire_04", [[Interface\Addons\SharedMedia_MyMedia\sound\WeaponFire_04.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "WeaponFire_06", [[Interface\Addons\SharedMedia_MyMedia\sound\WeaponFire_06.ogg]], LSM.LOCALE_BIT_koKR) 
LSM:Register("sound", "Yellow", [[Interface\Addons\SharedMedia_MyMedia\sound\Yellow.ogg]], LSM.LOCALE_BIT_koKR) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "aggro_bar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\aggro_bar.tga]]) 
LSM:Register("statusbar", "customdetails", [[Interface\Addons\SharedMedia_MyMedia\statusbar\customdetails.tga]]) 
LSM:Register("statusbar", "hp", [[Interface\Addons\SharedMedia_MyMedia\statusbar\hp.tga]]) 
LSM:Register("statusbar", "Neon_Bar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Neon_Bar.tga]]) 
LSM:Register("statusbar", "Neon_Bar1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Neon_Bar1.tga]]) 
LSM:Register("statusbar", "Rainbow2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Rainbow2.tga]]) 
LSM:Register("statusbar", "Simpy1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy1.tga]]) 
LSM:Register("statusbar", "Simpy10", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy10.tga]]) 
LSM:Register("statusbar", "Simpy11", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy11.tga]]) 
LSM:Register("statusbar", "Simpy12", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy12.tga]]) 
LSM:Register("statusbar", "Simpy13", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy13.tga]]) 
LSM:Register("statusbar", "Simpy14", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy14.tga]]) 
LSM:Register("statusbar", "Simpy15", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy15.tga]]) 
LSM:Register("statusbar", "Simpy16", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy16.tga]]) 
LSM:Register("statusbar", "Simpy17", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy17.tga]]) 
LSM:Register("statusbar", "Simpy18", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy18.tga]]) 
LSM:Register("statusbar", "Simpy19", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy19.tga]]) 
LSM:Register("statusbar", "Simpy2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy2.tga]]) 
LSM:Register("statusbar", "Simpy20", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy20.tga]]) 
LSM:Register("statusbar", "Simpy3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy3.tga]]) 
LSM:Register("statusbar", "Simpy4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy4.tga]]) 
LSM:Register("statusbar", "Simpy5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy5.tga]]) 
LSM:Register("statusbar", "Simpy6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy6.tga]]) 
LSM:Register("statusbar", "Simpy7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy7.tga]]) 
LSM:Register("statusbar", "Simpy8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy8.tga]]) 
LSM:Register("statusbar", "Simpy9", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Simpy9.tga]]) 
LSM:Register("statusbar", "Tukui", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Tukui.tga]]) 
LSM:Register("statusbar", "Wagerssi", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wagerssi.tga]]) 
LSM:Register("statusbar", "Wagerssi1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wagerssi1.tga]]) 
LSM:Register("statusbar", "Wagerssi2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wagerssi2.tga]]) 
LSM:Register("statusbar", "Wagerssi3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wagerssi3.tga]]) 
LSM:Register("statusbar", "Wagerssi4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wagerssi4.tga]]) 
